services:
  - type: web
    name: latex-compiler
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra && \
      pip install -r requirements.txt
    startCommand: python app.py
